#!/bin/sh

if [ -z "$VAULT_TLS_KEY" -a -z "$VAULT_TLS_CERT" ]; then
  openssl genrsa -out /tmp/server-key.pem 2048
  openssl req -new -key /tmp/server-key.pem -out /tmp/server-csr.pem \
    -subj /CN=*/
  openssl x509 -req -in /tmp/server-csr.pem -out /tmp/server-cert.pem \
    -signkey /tmp/server-key.pem -days 3650
elif [ test -f "$VAULT_TLS_KEY" && test -f "$VAULT_TLS_CERT" ]; then
  echo "Symlinking TLS key from VAULT_TLS_KEY"
  ln -sf $VAULT_TLS_KEY /tmp/server-key.pem
  echo "Symlinking TLS cert from VAULT_TLS_CERT"
  ln -sf $VAULT_TLS_CERT /tmp/server-cert.pem
else
  echo "Writing TLS key from VAULT_TLS_KEY"
  echo $VAULT_TLS_KEY > /tmp/server-key.pem
  echo "Writing TLS cert from VAULT_TLS_CERT"
  echo $VAULT_TLS_CERT > /tmp/server-cert.pem
fi
